// constant/sampleData.ts

export const sampleData = [
    {
      id: 1,
      name: "MunchLunch Cafe",
      tags: "Chicken, Fastfood, Rice",
      rating: 3.4,
      reviews: "27+ Ratings",
      discount: "5% off order",
      image: "/images/1.jpg",
      location: "Ikeja, Lagos",
      opensAt: "09:00",
      closesAt: "22:30",
      notice: "Special discounts available today!",
    },
    {
      id: 2,
      name: "Westmead Royal Bites - Bodija",
      tags: "Rice, Pounded Yam",
      rating: 3.7,
      reviews: "401+ Ratings",
      discount: "Free delivery, up to ₦500",
      image: "/images/2.jpg",
      location: "Yaba, Lagos",
      opensAt: "10:00",
      closesAt: "20:00",
    },
    {
      id: 3,
      name: "Calabar Igbo Ro",
      tags: "Rice, Goat meat, Fastfood",
      rating: 2.3,
      reviews: "2+ Ratings",
      discount: "Delivery is cu...",
      image: "/images/3.jpg",
      location: "Surulere, Lagos",
      opensAt: "08:30",
      closesAt: "21:00",
    },
    {
      id: 4,
      name: "Spicy Delight",
      tags: "Spicy, Chicken, Fries",
      rating: 4.5,
      reviews: "150+ Ratings",
      discount: "10% off first order",
      image: "/images/4.jpg",
      location: "Lekki, Lagos",
      opensAt: "11:00",
      closesAt: "21:00",
    },
    {
      id: 5,
      name: "Urban Tastes",
      tags: "Burgers, Pizza, Drinks",
      rating: 4.0,
      reviews: "89+ Ratings",
      discount: "Buy 1 Get 1 Free",
      image: "/images/5.jpg",
      location: "Victoria Island, Lagos",
      opensAt: "10:00",
      closesAt: "23:00",
    },
    {
      id: 6,
      name: "Mama's Kitchen",
      tags: "Local, Soups, Swallow",
      rating: 3.8,
      reviews: "300+ Ratings",
      discount: "Free delivery on weekends",
      image: "/images/6.jpg",
      location: "Ajah, Lagos",
      opensAt: "08:00",
      closesAt: "20:00",
    },
    {
      id: 7,
      name: "Tropical Treats",
      tags: "Smoothies, Desserts",
      rating: 4.7,
      reviews: "50+ Ratings",
      discount: "15% off orders above ₦2000",
      image: "/images/7.jpg",
      location: "Maryland, Lagos",
      opensAt: "09:30",
      closesAt: "20:00",
    },
    {
      id: 8,
      name: "Grill Master",
      tags: "Barbecue, Grilled Fish",
      rating: 4.2,
      reviews: "120+ Ratings",
      discount: "Free drink with every order",
      image: "/images/8.jpg",
      location: "Ogba, Lagos",
      opensAt: "10:00",
      closesAt: "22:00",
    },
    {
      id: 9,
      name: "Rice Bowl Express",
      tags: "Rice, Chicken, Fastfood",
      rating: 4.1,
      reviews: "200+ Ratings",
      discount: "20% off orders above ₦3000",
      image: "/images/9.jpg",
      location: "Festac, Lagos",
      opensAt: "08:30",
      closesAt: "21:30",
    },
    {
      id: 10,
      name: "Golden Spoon",
      tags: "Rice, Seafood, Local",
      rating: 3.9,
      reviews: "150+ Ratings",
      discount: "Free delivery on first order",
      image: "/images/10.jpg",
      location: "Oshodi, Lagos",
      opensAt: "09:00",
      closesAt: "22:00",
    },
    {
      id: 11,
      name: "Jollof Junction",
      tags: "Rice, Jollof, Plantain",
      rating: 4.3,
      reviews: "300+ Ratings",
      discount: "Buy 2 Get 1 Free",
      image: "/images/11.jpg",
      location: "Ikorodu, Lagos",
      opensAt: "10:00",
      closesAt: "20:30",
    },
    {
      id: 12,
      name: "Rice & Spice",
      tags: "Rice, Spicy, Chicken",
      rating: 4.0,
      reviews: "180+ Ratings",
      discount: "10% off orders above ₦5000",
      image: "/images/12.jpg",
      location: "Gbagada, Lagos",
      opensAt: "09:00",
      closesAt: "21:00",
    },
    {
      id: 13,
      name: "Village Pot",
      tags: "Rice, Local, Soups",
      rating: 3.6,
      reviews: "120+ Ratings",
      discount: "Free drink with every meal",
      image: "/images/13.jpg",
      location: "Alimosho, Lagos",
      opensAt: "08:00",
      closesAt: "19:30",
    },
    {
      id: 14,
      name: "Royal Rice Hub",
      tags: "Rice, Fried Rice, Chicken",
      rating: 4.4,
      reviews: "250+ Ratings",
      discount: "5% off all orders",
      image: "/images/14.jpg",
      location: "Iyana Ipaja, Lagos",
      opensAt: "09:00",
      closesAt: "22:00",
    },
    {
      id: 15,
      name: "Rice Delight",
      tags: "Rice, Goat Meat, Fastfood",
      rating: 4.2,
      reviews: "100+ Ratings",
      discount: "Free delivery on weekends",
      image: "/images/15.jpg",
      location: "Ogudu, Lagos",
      opensAt: "10:00",
      closesAt: "21:00",
    },
    {
      id: 16,
      name: "Beverage Bliss",
      tags: "Drinks, Smoothies, Desserts",
      rating: 4.6,
      reviews: "75+ Ratings",
      discount: "Free drink with every dessert",
      image: "/images/16.jpg",
      location: "Ojodu, Lagos",
      opensAt: "09:00",
      closesAt: "21:00",
    },
    {
      id: 17,
      name: "Chop & Sip",
      tags: "Snacks, Drinks, Fastfood",
      rating: 4.3,
      reviews: "90+ Ratings",
      discount: "Free drink with every snack",
      image: "/images/17.jpg",
      location: "Shomolu, Lagos",
      opensAt: "10:00",
      closesAt: "22:00",
    },
    {
      id: 18,
      name: "Grill & Chill",
      tags: "Barbecue, Drinks, Grilled Fish",
      rating: 4.5,
      reviews: "110+ Ratings",
      discount: "Free drink with every barbecue",
      image: "/images/18.jpg",
      location: "Ebute Metta, Lagos",
      opensAt: "11:00",
      closesAt: "23:00",
    },
  ];
  